version: '3'

services:
  mysql:
    image: mysql:5
    container_name: mysql5_container
    environment:
      MYSQL_ROOT_PASSWORD: rinha-db
      MYSQL_DATABASE: rinha-db
      MYSQL_USER: rinha-db
      MYSQL_PASSWORD: rinha-db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: